### ISSUE TITLE
Documentation: Linux Mint + wakepy behaviour when battery dies while wakelock set

### ISSUE THREAD

**Issue by Stehlampe2020** [np-8/wakepy#19]
I had my battery running low on my laptop with Linux Mint 21.1 with Cinnamon.   
I set the lock and waited.   
When the battery reached 2% the computer shut down as if I had pressed "Shut Down" even though the setting what to do when the battery dies was set to "Do Nothing". 
After starting up again the option "suspend" was missing from the power menu, pressing the power button (set to suspend) did nothing and `systemctl suspend` errored out. Everything returned to normal after running `wakepi.unset_keepawake()` in Python3, even though I set the lock with 
```python3
import wakepy, time
with wakepy.keepawake(True):
    while True:
        time.sleep(3)
        print('Another 3 seconds!')
```

**Comment by np-8** [comment]
Hi @Stehlampe2020 ,

Thanks for the information! I will update your findings to the docs at some point (or, if you want, you can supply a PR).

- Niko

**Comment by Stehlampe2020** [comment]
Because `wakepy` masks all ways for a Linux computer with `systemd` to suspend or similar that option is immediately disabled in any dialog as soon as the wakelock is set, suspending/hibernating becomes only possible after releasing of the wakelock.   
It's not just after the reboot that the suspend button disappeares.

**Comment by Stehlampe2020** [comment]
@np-8 I created a PR, #21.
