### ISSUE TITLE
Documentation: Ubuntu Unity 22.04 on iMac + wakelock

### ISSUE THREAD

**Issue by Stehlampe2020** [np-8/wakepy#20]
Ubutu Unity 22.04 locks and turns off the screen (and forgets the screen brightness, which it always does on my iMac when the screen got turned off) after the set timeout even after running and not cancelling `wakepy -s`.   
The "Suspend" system menu entry does nothing.

**Comment by np-8** [comment]
@Stehlampe2020  Was this already included in the PR's you provided?

**Comment by Stehlampe2020** [comment]
@np-8 I included my research there, yes.   
I didn't close this issue because I just forgot about it, sorry...

**Comment by np-8** [comment]
No problem and thanks!
