### ISSUE TITLE
Context manager

### ISSUE THREAD

**Issue by bubblefoil** [np-8/wakepy#5]
Hi, wouldn't it make sense to treat the disabled sleep mode as context, which could be returned by `set_keepawake()` and used for automatic `unset_keepawake()`?

**Comment by np-8** [comment]
I was thinking this a bit when I did the initial version. I think having a context manager version could make sense. Although, the `set_keepawake()` and `unset_keepawake()` are probably also needed:
- Function approach (`set_keepawake()` and `unset_keepawake()`) is easy to understand even for beginners.
- Function approach makes it possible to set the keepawake on one thread/process, and unset in some other thread/process. 

The context manager approach has the positive of being a bit less verbose especially if there is some error handling. Do you see other benefits? It could be implemented as

```python
with keepawake(**params):
    # do stuff
```
and it could use the `set_keepawake()` and `unset_keepawake()` under the hood.

That being said, one day it might be interesting to have multiprocessing-supporting approach that uses a counter under the hood; for each `set_keepawake()` call there should be `unset_keepawake()` and for example if one calls `set_keepawake()`  three times, the  `unset_keepawake()`  should be called three times before it would actually bet unset. In current implementation, if there were three long running processes (2hrs, 30hrs and 30hrs), and all of them would be using  `unset_keepawake()`, PC would sleep soon after 2hrs.

**Comment by HoustonFortney** [comment]
Amazing timing. I actually was looking for the same thing in this library today. I think this would make my code that is consuming this library more readable. It seems to fit the general motivations for context managers outlined in [PEP 343](https://www.python.org/dev/peps/pep-0343/).

I made a PR if you are open to adding this. I did not address the multi-thread/process case you mentioned.

**Comment by np-8** [comment]
Thanks for the PR! The context manager is now part of 0.4.0 and available in PyPI.

**Comment by bubblefoil** [comment]
Awesome, thanks!
