### ISSUE TITLE
Loading module on Linux raise `FileNotFoundError: [Errno 2] No such file or directory: 'pidof systemd'`

### ISSUE THREAD

**Issue by ikus060** [np-8/wakepy#8]
When trying to load this module on Linux system with systemd, the module fail with the following trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pidof systemd'
```

The line `subprocess.check_output('pidof systemd')` should be replace by `subprocess.check_output(['pidof','systemd'])`

**Comment by np-8** [comment]
Thanks for the report! Fixed in https://github.com/np-8/wakepy/commit/d56b1280981238f7dc6bae7ebb5122016b634b52. Pushed the fix in wakepy 0.4.1 in PyPI.

**Comment by ikus060** [comment]
Thanks alot for the quick fix !

I might provide you a dbus implementation for Linux, because systemctl may prompt for credentials.

**Comment by np-8** [comment]
That sounds awesome!
